const garage = { capacity: 48, baseRate: 4, sessions: [{ id: "PF-1842", plate: "KJH 4821", type: "SUV", slot: "A-12", entry: "2026-09-12T07:42" }, { id: "PF-1843", plate: "MNP 9087", type: "Car", slot: "A-08", entry: "2026-09-12T08:16" }, { id: "PF-1844", plate: "RXT 2110", type: "Car", slot: "B-03", entry: "2026-09-12T08:44" }, { id: "PF-1845", plate: "WQK 7602", type: "SUV", slot: "B-14", entry: "2026-09-12T09:05" }, { id: "PF-1846", plate: "LMA 3318", type: "Car", slot: "C-07", entry: "2026-09-12T09:28" }, { id: "PF-1847", plate: "HCD 4429", type: "Motorcycle", slot: "C-11", entry: "2026-09-12T10:12" }, { id: "PF-1848", plate: "NVS 1294", type: "Car", slot: "A-04", entry: "2026-09-12T10:32" }, { id: "PF-1849", plate: "PQR 6750", type: "Car", slot: "B-09", entry: "2026-09-12T10:48" }], slots: ["A-01", "A-02", "A-03", "A-04", "A-05", "A-06", "A-07", "A-08", "A-09", "A-10", "A-11", "A-12", "B-01", "B-02", "B-03", "B-04", "B-05", "B-06", "B-07", "B-08", "B-09", "B-10", "B-11", "B-12", "B-13", "B-14", "C-01", "C-02", "C-03", "C-04", "C-05", "C-06", "C-07", "C-08", "C-09", "C-10", "C-11", "C-12"] };
const $ = (selector) => document.querySelector(selector);
const money = (value) => `$${value.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
const occupiedSlots = () => new Set(garage.sessions.map((session) => session.slot));
function durationText(entry) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(entry).getTime()) / 60000)); return `${Math.floor(minutes / 60)}h ${String(minutes % 60).padStart(2, "0")}m`; }
function calculatePrice(entry, exit = new Date()) { const minutes = Math.max(15, Math.ceil((exit - new Date(entry)) / 60000)); return Math.ceil(minutes / 60) * garage.baseRate; }
function renderSessions() { $("#sessions-table").innerHTML = garage.sessions.map((session) => `<tr><td><strong>${session.plate}</strong><small>${session.id} · ${session.type}</small></td><td><span class="slot-label">${session.slot}</span></td><td>${new Date(session.entry).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td><td class="mono">${durationText(session.entry)}</td><td><strong>${money(calculatePrice(session.entry))}</strong></td><td><span class="status-pill active">Active</span></td><td><button class="row-action" data-checkout="${session.id}" aria-label="Check out ${session.plate}">→</button></td></tr>`).join(""); $("#active-value").textContent = garage.sessions.length; $("#nav-session-count").textContent = garage.sessions.length; document.querySelectorAll("[data-checkout]").forEach((button) => button.addEventListener("click", () => checkout(button.dataset.checkout))); }
function renderSlots() { const occupied = occupiedSlots(); const available = garage.capacity - occupied.size; $("#occupied-value").textContent = occupied.size; $("#occupancy-rate").textContent = `${((occupied.size / garage.capacity) * 100).toFixed(1)}%`; $("#occupancy-bar-fill").style.width = `${(occupied.size / garage.capacity) * 100}%`; $("#layout-available").textContent = available; $("#slot-map").innerHTML = garage.slots.map((slot, index) => `<button class="parking-slot ${occupied.has(slot) ? "occupied" : index === 17 ? "reserved" : "available"}" title="${slot} · ${occupied.has(slot) ? "Occupied" : index === 17 ? "Reserved" : "Available"}">${slot.replace("-", "")}</button>`).join(""); $("#slot-input").innerHTML = garage.slots.filter((slot) => !occupied.has(slot)).map((slot) => `<option value="${slot}">${slot}</option>`).join(""); }
function openCheckin() { const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); $("#entry-input").value = now.toISOString().slice(0, 16); renderSlots(); $("#checkin-modal").showModal(); $("#plate-input").focus(); }
function checkout(id) { const session = garage.sessions.find((item) => item.id === id); if (!session) return; const amount = calculatePrice(session.entry); if (!window.confirm(`Check out ${session.plate} from ${session.slot} for ${money(amount)}?\n\nPayment is recorded as pending for the future provider integration.`)) return; garage.sessions = garage.sessions.filter((item) => item.id !== id); renderAll(); showToast(`${session.plate} checked out · ${money(amount)} pending payment`); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 3600); }
function renderAll() { renderSessions(); renderSlots(); }
$("#checkin-form").addEventListener("submit", (event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); const plate = formData.get("plate").trim().toUpperCase(); const slot = formData.get("slot"); if (!plate || !slot) return; garage.sessions.unshift({ id: `PF-${1850 + garage.sessions.length}`, plate, type: formData.get("vehicleType"), slot, entry: formData.get("entryTime") }); event.currentTarget.reset(); $("#checkin-modal").close(); renderAll(); showToast(`${plate} checked in to ${slot}`); });
document.querySelectorAll("#open-checkin, #open-checkin-strip").forEach((button) => button.addEventListener("click", openCheckin));
document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { const view = button.dataset.view; if (view === "overview") { $("#overview-view").classList.remove("hidden"); $("#generic-view").classList.add("hidden"); $("#page-title").textContent = "Overview"; return; } $("#overview-view").classList.add("hidden"); $("#generic-view").classList.remove("hidden"); const title = button.textContent.trim().replace(/[0-9]/g, ""); $("#page-title").textContent = title; $("#generic-title").textContent = title; $("#generic-heading").textContent = title; }));
renderAll();